---
apiVersion: apps/v1 
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
  labels:
    app: {{ .Values.serviceName }}
    version: "{{ .Values.imageTag }}"
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.numOfPods | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
      labels:
        app: {{ .Values.serviceName }}
        version: "{{ .Values.imageTag }}"
        date: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      {{- if (.Values.acrSecretName) }} 
      imagePullSecrets:
        - name: {{ .Values.acrSecretName }}
      {{- end }}
      hostNetwork: true
      containers:
      - env:
        - name: KDC_PASSWORD
          valueFrom:
           secretKeyRef:
            name: {{ .Values.serviceName }}-secrets
            key: kdcPassword
        - name: KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: HELM_RELEASE_TIME
          value: "{{ date "20060102-150405" .Release.Time }}"
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: REALM
          value: PEGACORN-FHIRPLACE-AUDIT.LOCAL
        image: {{ .Values.dockerRepo }}pegacorn-fhirplace-kdcserver:{{ .Values.imageTag }}            
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        livenessProbe:
          tcpSocket:
            port: 88
          initialDelaySeconds: 15
        name: kdc-server
        ports:
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 88
          name: kdc
          protocol: TCP
        - containerPort: 749
          name: kdc-admin
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 88
          initialDelaySeconds: 15
        securityContext:
          privileged: false
        volumeMounts:
        - name: keytabs
          mountPath: /etc/security/keytabs
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      volumes:
      - name: keytabs
        hostPath:
          path: {{ .Values.hostPathKeytab }}
