---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if (.Values.dnsEntry) }} 
    # From https://docs.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer
    service.beta.kubernetes.io/azure-load-balancer-internal: "{{ .Values.loadBalancerInternal | default true }}"
#    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.dnsEntry }}
    # From https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsEntry }}
    {{- end }}    
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: {{ .Values.serviceName }}
    version: "{{ .Values.imageTag }}"
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: kdc
    port: 88
    protocol: TCP
    targetPort: 88
  - name: kdc-admin
    port: 749
    protocol: TCP
    targetPort: 749
  - name: supervisor
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: {{ .Values.serviceName }}
  type: {{ .Values.serviceType | default "LoadBalancer" }}
  {{- if (.Values.loadBalancerIP) }} 
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
